global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "amazing-gitlab-exporter"
    scrape_interval: 30s
    scrape_timeout: 25s
    metrics_path: /metrics
    static_configs:
      - targets: ["exporter:8080"]
        labels:
          instance: "age"

  - job_name: "prometheus"
    scrape_interval: 60s
    static_configs:
      - targets: ["localhost:9090"]
