apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amazing-gitlab-exporter.fullname" . }}-config
  namespace: {{ .Release.Namespace | default "amazing-gitlab-exporter" }}
  labels:
    {{- include "amazing-gitlab-exporter.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- .Values.exporterConfig | toYaml | nindent 4 }}
