{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "amazing-gitlab-exporter.fullname" . }}
  namespace: {{ .Release.Namespace | default "amazing-gitlab-exporter" }}
  labels:
    {{- include "amazing-gitlab-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "amazing-gitlab-exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
