{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "amazing-gitlab-exporter.fullname" . }}
  namespace: {{ .Release.Namespace | default "amazing-gitlab-exporter" }}
  labels:
    {{- include "amazing-gitlab-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "amazing-gitlab-exporter.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  {{- end }}
{{- end }}
