{{- if and .Values.route.enabled (.Capabilities.APIVersions.Has "route.openshift.io/v1") -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "amazing-gitlab-exporter.fullname" . }}
  namespace: {{ .Release.Namespace | default "amazing-gitlab-exporter" }}
  labels:
    {{- include "amazing-gitlab-exporter.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  path: {{ .Values.route.path | default "/" }}
  to:
    kind: Service
    name: {{ include "amazing-gitlab-exporter.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- with .Values.route.tls }}
  tls:
    termination: {{ .termination | default "edge" }}
    {{- if .insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
