{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amazing-gitlab-exporter.fullname" . }}
  namespace: {{ .Release.Namespace | default "amazing-gitlab-exporter" }}
  labels:
    {{- include "amazing-gitlab-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  gitlab-token: {{ .Values.gitlabToken | b64enc | quote }}
  {{- if .Values.webhookSecretToken }}
  webhook-secret: {{ .Values.webhookSecretToken | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.redis.enabled) .Values.externalRedis.url }}
  redis-url: {{ .Values.externalRedis.url | b64enc | quote }}
  {{- end }}
{{- end }}
